import { Box, Center, Flex, Img, Text } from "@chakra-ui/react";
import React from "react";
import { Tilt } from "react-tilt";

function Skills(props) {
    return (
        <Flex
            pt={100}
            alignItems={"center"}
            id="skills"
            flexDirection={"column"}
            justifyContent={"center"}
        >
            <Text fontWeight={"bold"} color={"#EEEEEE"} fontSize={30}>
                My{" "}
                <Text as={"span"} color={"#00ADB5"}>
                    Technical Skills
                </Text>
            </Text>
            <Flex
                color={"#EEEEEE"}
                m={10}
                mt={90}
                gap={20}
                flexWrap={"wrap"}
                justifyContent={"center"}
                w={["95%", "70%"]}
            >
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://cdn-icons-png.flaticon.com/128/174/174854.png"
                                w={"95%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">HTML</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://cdn-icons-png.flaticon.com/128/5968/5968242.png"
                                w={"95%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">CSS</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://cdn-icons-png.flaticon.com/128/5968/5968292.png"
                                w={"80%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">Javascript</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://mohitkss.github.io/static/media/react.22d1f2096ed82cab7a8a.png"
                                w={"95%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">React</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://mohitkss.github.io/static/media/redux.7fec6369cecd1cbd44d6.png"
                                w={"95%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">Redux</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://i.imgur.com/nNdmdXI.png"
                                w={"100%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">ChakraUI</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://mohitkss.github.io/static/media/nodejs.b508473ad71a31ce2fae.png"
                                w={"95%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">NodeJS</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://www.vectorlogo.zone/logos/expressjs/expressjs-icon.svg"
                                w={"95%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">Express</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://mohitkss.github.io/static/media/mongodb.4f7af09e6354d51beec8.png"
                                w={"70%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">MongoDB</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://cdn-icons-png.flaticon.com/512/226/226777.png"
                                w={"80%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">Java</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://cdn-icons-png.flaticon.com/512/5968/5968350.png"
                                w={"70%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">Python</Text>
                        </Center>
                    </Flex>
                </Tilt>
            </Flex>
            <Flex
                pt={100}
                alignItems={"center"}
                flexDirection={"column"}
                justifyContent={"center"}
            >
                <Text fontWeight={"bold"} color={"#EEEEEE"} fontSize={30}>
                    Tools{" "}
                    <Text as={"span"} color={"#00ADB5"}>
                        &{" "}
                    </Text>
                    Platforms
                </Text>
                <Flex
                    color={"#EEEEEE"}
                    m={10}
                    mt={90}
                    gap={20}
                    flexWrap={"wrap"}
                    justifyContent={"center"}
                    w={["95%", "70%"]}
                >
                    <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://cdn-icons-png.flaticon.com/512/906/906324.png"
                                w={"95%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">VS code</Text>
                        </Center>
                    </Flex>
                </Tilt>
                <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://rangav.gallerycdn.vsassets.io/extensions/rangav/vscode-thunder-client/2.7.4/1685715470089/Microsoft.VisualStudio.Services.Icons.Default"
                                w={"70%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">T-Client</Text>
                        </Center>
                    </Flex>
                    </Tilt>
                    <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://static-00.iconduck.com/assets.00/npm-icon-512x512-qtfdrf37.png"
                                w={"80%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">NPM</Text>
                        </Center>
                    </Flex>
                    </Tilt>
                    <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={5}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://cdn-icons-png.flaticon.com/512/4494/4494748.png"
                                w={"80%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name">GIT</Text>
                        </Center>
                    </Flex>
                    </Tilt>
                    <Tilt>
                    <Flex
                        justifyContent={"center"}
                        alignItems={"center"}
                        transform={"rotate(45deg)"}
                        p={1}
                        h={100}
                        w={100}
                        backgroundColor={"#393E46"}
                        cursor={"pointer"}
                        _hover={{
                            "box-shadow":
                                "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;",
                        }}
                    >
                        <Center
                            flexDirection={"column"}
                            transform={"rotate(-45deg)"}
                            className="skills-card"
                        >
                            <Img
                                className="skills-card-img"
                                src="https://i.imgur.com/rbpW9zy.png"
                                w={"80%"}
                                display={"block"}
                            />
                            <Text className="skills-card-name" mt={-5}>AWS</Text>
                        </Center>
                    </Flex>
                    </Tilt>
                </Flex>
            </Flex>
        </Flex>
    );
}

export default Skills;
